# Generated by Django 2.1.7 on 2020-01-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuserdata',
            fields=[
                ('id', models.IntegerField(auto_created=True, db_column='id', primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=200)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('operation', models.IntegerField()),
            ],
            options={
                'db_table': 'Cuserdata',
            },
        ),
    ]
