# Generated by Django 2.1.7 on 2020-01-09 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('ActivityDate', models.DateField(null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('createDate', models.DateField(auto_now_add=True)),
                ('enable', models.BooleanField(default=True)),
                ('isAttest', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RecruitJoinedUserList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RecruitSignupUserList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.IntegerField(auto_created=True, db_column='id', primary_key=True, serialize=False)),
                ('do', models.FloatField(db_column='do')),
            ],
            options={
                'db_table': 'test',
            },
        ),
        migrations.CreateModel(
            name='TrainActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200, null=True)),
                ('ActivityDate', models.DateField(null=True)),
                ('createDate', models.DateField(auto_now_add=True)),
                ('enable', models.BooleanField(default=True)),
                ('isAttest', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TrainJoinedUserList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TrainSignupUserList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AID.TrainActivity')),
            ],
        ),
        migrations.CreateModel(
            name='yali',
            fields=[
                ('id', models.IntegerField(auto_created=True, db_column='id', primary_key=True, serialize=False)),
                ('press', models.FloatField(db_column='press')),
            ],
            options={
                'db_table': 'yali',
            },
        ),
    ]
