# Generated by Django 2.1.7 on 2020-01-09 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AID', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainsignupuserlist',
            name='SignUser',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainjoineduserlist',
            name='Activity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AID.TrainActivity'),
        ),
        migrations.AddField(
            model_name='trainjoineduserlist',
            name='SignUser',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainactivity',
            name='User',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recruitsignupuserlist',
            name='Activity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AID.TrainActivity'),
        ),
        migrations.AddField(
            model_name='recruitsignupuserlist',
            name='SignUser',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recruitjoineduserlist',
            name='Activity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AID.TrainActivity'),
        ),
        migrations.AddField(
            model_name='recruitjoineduserlist',
            name='SignUser',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recruitactivity',
            name='User',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
