# Generated by Django 2.1.7 on 2019-09-01 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default='匿名网友', max_length=20)),
                ('message', models.TextField()),
                ('del_pwd', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('情感', '0'), ('生活', '1'), ('技术', '2'), ('新闻', '3'), ('幽默', 4), ('其它', '5')], max_length=2)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('enable', models.BooleanField(default=True)),
            ],
        ),
    ]
