# Generated by Django 2.1.7 on 2019-09-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gender', models.CharField(choices=[('男', 'm'), ('女', 'w')], max_length=2)),
                ('password', models.CharField(max_length=30)),
                ('enable', models.BooleanField(default=True)),
            ],
        ),
    ]
