# Generated by Django 2.1.7 on 2020-01-09 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'v_classification',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('desc', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(max_length=255, upload_to='')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='cover/')),
                ('status', models.CharField(blank=True, choices=[('0', '发布中'), ('1', '未发布')], max_length=1, null=True)),
                ('view_count', models.IntegerField(blank=True, default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True, max_length=20)),
                ('classification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='video.Classification')),
                ('collected', models.ManyToManyField(blank=True, related_name='collected_videos', to=settings.AUTH_USER_MODEL)),
                ('liked', models.ManyToManyField(blank=True, related_name='liked_videos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'v_video',
            },
        ),
    ]
