# Generated by Django 2.1.7 on 2019-08-15 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='isDelete',
            field=models.BooleanField(default=False),
        ),
    ]
