# Generated by Django 2.1.7 on 2019-09-01 04:31

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('testapp1', '0002_students_isdelete'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='classes',
            managers=[
                ('classobj', django.db.models.manager.Manager()),
            ],
        ),
    ]
